name: docker

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define image tag
        run: date -u +"%Y-%m-%d-%H-%M-%S" > tag

      - name: Docker Build
        run: docker build . --tag ghcr.io/lbguilherme/dbup-cli:$(cat tag) --tag ghcr.io/lbguilherme/dbup-cli:latest --pull

      - name: Docker Push
        run: |
          docker push ghcr.io/lbguilherme/dbup-cli:$(cat tag)
          docker push ghcr.io/lbguilherme/dbup-cli:latest
